# Rock, Paper, Scissors

In this week's exercise you will be working with TFDS and the rock-paper-scissors dataset. You'll do a few tasks such as loading the dataset, preprocess it and train a simple CNN model on it.


## Setup

In [ ]:
from os import getcwd

import tensorflow as tf
import tensorflow_datasets as tfds

In [ ]:
# EXERCISE: encoding the labels using our own function for one-hot encoding

def my_one_hot(feature, label):
    # Encode the labels to one-hot using tf.one_hot with depth equal to total 
    # number of classes here which are rock, paper and scissors
    
    one_hot = # YOUR CODE HERE
    return feature, one_hot

_,one_hot = my_one_hot(["a","b","c","a"],[1,2,3,1])
print(one_hot)


## Expected Output
```
tf.Tensor(
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 1. 0.]], shape=(4, 3), dtype=float32)
 ```

In [ ]:
# EXERCISE: Loading the rock, paper and scissors train and test dataset using tfds.load. 

# Use data_dir=filepath as the dataset is already downloaded for you

filePath = f"{getcwd()}/../tmp2"

train_data = tfds.load(# YOUR CODE HERE)
val_data = tfds.load(# YOUR CODE HERE)
    
train_data_len = len(list(train_data))
val_data_len = len(list(val_data))

print(train_data_len)
print(val_data_len)

## Expected Output
```
2520
372
 ```

In [ ]:
# EXERCISE: one-hot encode the train and validation labels using the function we defined earlier

# HINT - use map function https://www.tensorflow.org/api_docs/python/tf/data/Dataset#map

train_data = # YOUR CODE HERE
val_data = # YOUR CODE HERE

print(type(train_data))

## Expected Output
```
<class 'tensorflow.python.data.ops.dataset_ops.MapDataset'>
 ```

In [ ]:
# EXERCISE: Check the information about the dataset to see the dataset image shape

# HINT: Use with_info=True and data_dir
_,info = tfds.load(# YOUR CODE HERE)

print(info.features['image'].shape)

## Expected Output
```
(300, 300, 3)

 ```

In [ ]:
# EXERCISE: Train a simple CNN model on the dataset

train_batches = train_data.shuffle(100).batch(10)
validation_batches = val_data.batch(32)

model = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(16, (3, 3), activation='relu', input_shape=# YOUR CODE HERE),
    # You can define as many layers as you want
    # START CODE                        
                           
    # END CODE                       
    tf.keras.layers.Dense(# YOUR CODE HERE)
])

model.summary()


In [ ]:
# EXERCISE: Compile and fit your model - use categorical loss and choose optimizer as Adam

#Your final epoch training accuracy should be above 0.8 and validation accuracy above 0.4

model.compile(# YOUR CODE HERE)

history = model.fit(train_batches, epochs=10, validation_data=validation_batches, validation_steps=1)
    
print("Final Training Accuracy:-",history.history['accuracy'][-1])
print("Final Validation Accuracy:-",history.history['val_accuracy'][-1])

# Submission Instructions

In [ ]:
# Now click the 'Submit Assignment' button above.

# When you're done or would like to take a break, please run the two cells below to save your work and close the Notebook. This frees up resources for your fellow learners.

In [ ]:
%%javascript
<!-- Save the notebook -->
IPython.notebook.save_checkpoint();

In [ ]:
%%javascript
<!-- Shutdown and close the notebook -->
window.onbeforeunload = null
window.close();
IPython.notebook.session.delete();